import type { Capability, Grade, Topic } from '../core/cases';

/** 分类词汇：键与 core/cases 的分类类型一一对应。 */
export const gradeLabels: Record<Grade, string> = {
  1: '一年级',
  2: '二年级',
  3: '三年级',
  4: '四年级',
  5: '五年级',
  6: '六年级',
};

export const topicLabels: Record<Topic, string> = {
  'number-and-algebra': '数与代数',
  'shape-and-geometry': '图形与几何',
  'statistics-and-probability': '统计与概率',
  'integrated-practice': '综合与实践',
};

export const capabilityLabels: Record<Capability, string> = {
  'svg-2d': '二维图形',
  'canvas-2d': '连续绘制',
  'three-3d': '三维几何',
  'direct-manipulation': '直接操作',
  'parameter-control': '参数调节',
};

/** 应用外壳的界面文案。案例自身的教学内容随案例定义存放。 */
export const copy = {
  appName: '数学工具',
  brand: {
    name: 'Math Tools',
    tagline: '让数学，看得见',
    home: 'Math Tools · 返回案例库',
    navigation: '课堂互动案例',
  },
  library: {
    title: '案例库',
    eyebrow: '给好奇心一点空间',
    headline: '把抽象数学，变成',
    headlineAccent: '看得见的发现。',
    introduction: '从一条数轴到一个立方体，让学生在观察与操作中理解数学。选好案例，把探索带进课堂。',
    collectionTitle: '为下一次课堂，挑一个好案例',
    collectionDescription: '围绕知识点展开，跟着好奇心探索。',
    resultCount: (count: number) => `${count} 个案例`,
    clearFilters: '清除筛选',
    previewLabel: '数学，也可以这样看',
    previewCaption: '旋转 · 展开 · 发现空间关系',
    emptyHint: '试试其他关键词，或清除筛选查看全部案例。',
    searchLabel: '搜索案例',
    searchPlaceholder: '输入案例名称或关键词',
    gradeFilterLabel: '按年级筛选',
    topicFilterLabel: '按主题筛选',
    allGrades: '全部年级',
    allTopics: '全部主题',
    empty: '没有找到符合条件的案例。',
    viewDetail: '查看详情',
  },
  detail: {
    eyebrow: '课堂案例',
    preview: '案例示意',
    preparation: '课前准备',
    guidanceIntro: '几个简单操作，把思考留给学生。',
    objective: '教学目标',
    gradeRange: '适用年级',
    guidance: '操作指引',
    classification: '分类',
    reviewTitle: '教学评审',
    reviewStatus: { pending: '待评审', approved: '已通过评审' } as const,
    reviewTerminology: '使用术语',
    reviewParameterValidity: '参数有效性',
    reviewRisks: '误导风险与规避',
    enterPresentation: '进入演示',
    backToLibrary: '返回案例库',
  },
  presentation: {
    mode: '课堂演示',
    hint: '动手试一试，看看会发生什么',
    back: '返回',
    reset: '重置',
    fullscreen: '全屏',
    exitFullscreen: '退出全屏',
    help: '帮助',
    helpTitle: '操作指引',
    close: '关闭',
    collapseBar: '收起控制栏',
    expandBar: '展开控制栏',
    loading: '正在加载案例…',
    repairedNotice: (issues: string[]) => `链接中的参数已调整：${issues.join('；')}`,
    dismissNotice: '知道了',
  },
  footer: 'Math Tools · 让观察与思考，在课堂里发生。',
  cubeNet: {
    faces: { front: '前', back: '后', top: '上', bottom: '下', left: '左', right: '右' },
    resetView: '重置视角',
    grid: '参考网格',
    viewHint: '拖动旋转 · 滚轮或双指缩放',
    gridHint: '网格不表示实际尺寸',
    structureHint: '半透明观察：实线为可见棱，虚线为遮挡棱',
    unfoldAmount: '展开程度',
    fold: '折叠',
    unfold: '展开',
    sceneLabel: (unfold: number) => `三维场景：正方体展开图，当前展开程度 ${unfold}%`,
  },
  recovery: {
    unknownCaseTitle: '没有找到这个案例',
    unknownCaseBody: '链接中的案例不存在或已被移除。',
    caseFailureTitle: '案例加载失败',
    caseFailureBody: '这个案例暂时无法运行，其他案例不受影响。',
    retry: '重试',
    resetToDefaults: '恢复默认',
    backToLibrary: '返回案例库',
    notFoundTitle: '页面不存在',
  },
} as const;
